packages:
  # Applications
  - 'apps/*'

  # Shared libraries/packages
  - 'packages/*'

  # Edge applications
  - 'edge/*'
allowBuilds:
  esbuild: true
  protobufjs: true
  sharp: true
  supabase: true
  unrs-resolver: true
